### PR TITLE
Add some __aarch64__ functions

### PR DESCRIPTION
**Pull request by MaskRay**

### CODE REVIEW

**Comment by Zvictoria** [comment]
Hi, MaskRay.  Thanks a lot for your input My question is - how have you tested your changes? :) I don't have the corresponding tests and while I could add this patch easily I do need some evaluation.

**Comment by MaskRay** [comment]
These functions are used to validate the correctness of https://github.com/google/dimsum
We use llvm libFuzzer (https://github.com/google/dimsum/blob/master/dimsum_fuzz.cc ) for tests.

**Comment by MaskRay** [comment]
Also, these declarations look verbose to me:

```c
int64x2_t vsubl_s32(int32x2_t a, int32x2_t b); // VSUBL.S32 q0,d0,d0
_NEON2SSE_INLINE int64x2_t vsubl_s32(int32x2_t a, int32x2_t b) // VSUBL.S32 q0,d0,d0
```

If the first line really needed?

**Comment by Zvictoria** [comment]
Mega thanks ever! I will merge your commit for sure. As for declarations - I do need them for all compilers for some functions called by other functions in this header (they need to be declared in advance). For all other functions they are NOT required for all compilers. But I do remember one compiler tested expects them to be there - otherwise it gives compilation errors. It happens either in C or C++ mode and I don't remember which compiler it is... but the declarations should be there for it :)

**Comment by caand** [comment]
Late reply, but:

I think all these additions should not be conditioned by _NEON2SSE_64BIT.

This #define is for x86_64, while the changes translate armv8 intrinsics to any x86 (32bit also). It's the user's responsibility to avoid these intrinsics for armv7, but they can be used when targeting armv8, x86, or x86_64 (last two by including this header).

Best regards, Calin

**Pull request merged**
